language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t killthebee/client-test -f ./clientt/Dockerfile.dev ./clientt

after_succes:
  - docker build -t killthebee/complex-client ./clientt
  - docker build -t killthebee/complex-nginx ./nginx
  - docker build -t killthebee/complex-server ./server
  - docker build -t killthebee/complex-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push killthebee/complex-clientt
  - docker push killthebee/complex-nginx
  - docker push killthebee/complex-server
  - docker push killthebee/complex-worker